### ISSUE TITLE
In need of the DerefMut trait on RingBufferReader and RingBufferWriter

### ISSUE THREAD

**Issue by phstrauss** [RustAudio/rust-jack#197] opened 2024-07-12 11:03 UTC
Hello Will,

I miss, to keep both a RingBufferReader and RingBufferWriter in a struct using a RefCell, the DerefMut trait. The following code shows what I want to achieve:

```
use std::io;
use std::cell::RefCell;


struct RW<'a> {
    r: RefCell<&'a jack::RingBufferReader>,
    w: RefCell<&'a jack::RingBufferWriter>,
}

fn main() -> io::Result<()> {
    let ringbuf = jack::RingBuffer::new(1024).unwrap();
    let (mut reader, mut writer) = ringbuf.into_reader_writer();
    let rw = {
        RW {
            r: RefCell::new(&mut reader),
            w: RefCell::new(&mut writer),
        }
    };
    let buf = [0_u8, 1, 2, 3];
    let num = rw.w.borrow_mut().write_buffer(&buf);
    assert_eq!(num, buf.len());
    // Potentially in a another thread:
    let mut outbuf = [0_u8; 8];
    let num = reader.read_buffer(&mut outbuf);

    Ok(())
}
```

The compilation fails with:

```
error[E0596]: cannot borrow data in dereference of `RefMut<'_, &RingBufferWriter>` as mutable
  --> src/main.rs:20:15
   |
20 |     let num = rw.w.borrow_mut().write_buffer(&buf);
   |               ^^^^^^^^^^^^^^^^^ cannot borrow as mutable
   |
   = help: trait `DerefMut` is required to modify through a dereference, but it is not implemented for `RefMut<'_, &RingBufferWriter>`

For more information about this error, try `rustc --explain E0596`.
```

or:

```
error[E0596]: cannot borrow data in dereference of `RefMut<'_, &RingBufferWriter>` as mutable
  --> src/main.rs:20:15
   |
20 |     let num = (*(rw.w.borrow_mut())).write_buffer(&buf);
   |               ^^^^^^^^^^^^^^^^^^^^^^ cannot borrow as mutable
   |
   = help: trait `DerefMut` is required to modify through a dereference, but it is not implemented for `RefMut<'_, &RingBufferWriter>`

For more information about this error, try `rustc --explain E0596`.
```
Could you either implement or show me how to implement this trait, I'm beginning with Rust and don't know how to write such a thing. Thank you!

**Comment by wmedrano** [comment] 2024-09-12 01:27
I think the problem is that you are storing something of type `&T` in the RefCell, but you probably want to store `T` so that borrow_mut gives you something that is basically an `&mut T`.

Also, RefCell is not meant to be used to share things across multiple threads. What you probably want to do is to send the entire `RingBufferReader` and `RingBufferWriter` to a thread. Note, do not send a reference to the object as the lifetime can't be guaranteed when sending references so it won't compile.

**Comment by wmedrano** [comment] 2024-09-12 01:27
Closing as https://users.rust-lang.org/ is a better place for this kind of question.

**Closed by wmedrano** 2024-09-12 01:27 UTC
